package com.projectivesoftware.viewer.domain;

public enum IdentifierType {
    MEDHOST_ENTERPRISE_PATIENT_NUMBER,
    MEDHOST_ENTERPRISE_ENCOUNTER_NUMBER,
    CERNER_MILLENNIUM_PERSON_NUMBER,
    CERNER_MILLENNIUM_ENCOUNTER_NUMBER,
    CERNER_MILLENNIUM_FIN,
    CERNER_MILLENNIUM_MRN,
    HPF_PATIENT_NUMBER,
    HPF_ENCOUNTER_NUMBER
}
